[ch30655] amend indicator radio creation
unicef/etools-partner-reporting-portal pull request #1808
Opened 2022-08-09 07:36 UTC by domdinicola

[ch30655]

2022-08-09 07:37 UTC, domdinicola commented
Manual Script `IndicatorBlueprint.objects.filter(display_type=IndicatorBlueprint.RATIO).update(calculation_formula_across_locations='latest')`

2022-08-11 10:32 UTC, emaciupe approved these changes
looks good!

2022-08-12 17:57 UTC, acory commented on django_api/etools_prp/apps/unicef/tasks.py
> +                                            i['calculation_formula_across_locations'] = 'latest'
Pls re-check this change, as the card mentions calculation formula across `reporting periods`

2022-08-13 16:05 UTC, domdinicola commented on django_api/etools_prp/apps/unicef/tasks.py
> +                                            i['calculation_formula_across_locations'] = 'latest'
thx @acory :)

2022-08-18 14:16 UTC, robertavram commented
> calculation_formula_across_locations

calculation formula across reporting periods

2022-08-18 14:20 UTC, domdinicola commented
I changed that @acory @robertavram  thx!

2022-08-18 14:50 UTC, robertavram commented
This PR does not address the core of what is being asked. This card is actually related to [CH29826] 

https://app.shortcut.com/unicefetools/story/29826/prp-indicator-calculation-across-time-methods-should-include-latest


We need to add the option to select "Latest" as a calculation method across periods. Then we need to update the function that calculates this value to take into consideration the calculation method (right now it doesn't) `apps>indicator>models:L991`
The options need to be available on the model as well. (IndicatorBlueprint)

2022-08-25 13:26 UTC, robertavram requested changes
changes

2022-08-25 13:26 UTC, robertavram commented on django_api/etools_prp/apps/indicator/models.py
> +                reportable_total = accepted_indicator_reports.last().total
latest_accepted_indicator_report = accepted_indicator_reports.order_by('-time_period_start').first()

2022-08-25 13:26 UTC, robertavram commented on django_api/etools_prp/apps/unicef/tasks.py
> +                                        if 'display_type' in i and i['display_type'] == 'ratio':
percentage is taking the latest as well. so if `i['unit'] == "percentage"` you can set the calculation_formula_across_locations to 'latest'

2022-08-25 13:26 UTC, robertavram commented on django_api/etools_prp/apps/indicator/models.py
>                      reportable_total['v'] += indicator_report.total['v']
on L1018 it looks like both ratio and percentage are always calculated as latest across time periods. We should make sure that we can't set any other calculation methods for these indicators from the FE. If we will need to, then we'll have to come back and determine how that works.

2022-10-18 17:43 UTC, merged